name: BackendCI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        env:
          ENV_FILE_CONTENTS: ${{ secrets.ENV_FILE_CONTENTS }}
        working-directory: ./back-end
        run: |
          echo "$ENV_FILE_CONTENTS" > .env
          docker build -t backend .
        
      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.ERIC_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Tag and Push Backend Docker image to GHCR
        if: github.event_name == 'push'
        run: |
          # Convert repository name to lowercase
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker tag backend ghcr.io/$REPO_NAME/backend:latest
          docker push ghcr.io/$REPO_NAME/backend:latest
